#!/bin/sh

# This script simply provides shortcuts to common commands for mobile development
# Each platform script should be in separated into it's own file and called form here

APP_NAME=expoapp

# TODO remove this line in created project folder
if [ -d $APP_NAME ]; then cd $APP_NAME ;  fi

check_if_deno_installed() {
  which -s deno
  if [ ! $? = 0 ]; then
    echo "deno is not installed. Download from here:  https://github.com/denoland/deno/releases"
    echo "quick links:"
    echo "curl -L -O https://github.com/denoland/deno/releases/download/v2.2.11/deno-x86_64-unknown-linux-gnu.zip"
    echo "curl -L -O https://github.com/denoland/deno/releases/download/v2.2.11/deno-x86_64-apple-darwin.zip"
    exit 1
  fi
}

check_if_deno_installed


app_format() {
  if [ "$1" = "fix" ]; then
    deno fmt src/
  else
    deno fmt --check src/
  fi
}


app_lint() {
  if [ "$1" = "fix" ]; then
    deno lint --fix src/
  else
    deno lint src/
  fi
}


app_typecheck() {
  ./node_modules/.bin/tsc --noEmit --allowJs
  echo "Typecheck status: $?"
}


app_hook_link() {
  echo "Relinking hooks ..."
  if [ -f .git/hooks/pre-commit ]; then rm .git/hooks/pre-commit ; fi
  ln -s ../../_hooks/pre-commit .git/hooks/pre-commit
  echo "Done"
}


generate_svg_icons() {
  SVGR_CMD="./node_modules/.bin/svgr --native --typescript --out-dir"

  rm ./src/components/a_icons/*.ts? ./src/components/a_svg/*.ts?
  $SVGR_CMD ./src/components/a_icons ./src/assets/icons/
  $SVGR_CMD ./src/components/a_svg ./src/assets/svg/
}


# Install everything necesarry to prepare for CI testing or build
ci_install() {
  npm -g install pnpm
  pnpm install

  # TODO ensure deno is installed
}


# increment version number
ci_bump() {
  echo "TODO"
}

# send a message to slack about build progress
ci_slack() {
  echo "TODO"
}


# Build all or just Android or IOS from CI/CD pipeline
ci_build() {
  echo "TODO"
}


if [ "$1" = "create" ]; then . ./_scripts/run.create create ; exit $? ; fi

if [ "$1" = "format" ]; then app_format $2 ; exit $? ; fi
if [ "$1" = "lint" ]; then app_lint $2 ; exit $? ; fi
if [ "$1" = "typecheck" ]; then app_typecheck ; exit $? ; fi

if [ "$1" = "link-githook" ]; then app_hook_link; exit; fi

# Generators
if [ "$1" = "gen-svg" ]; then generate_svg_icons ; exit $? ; fi

# CI/CD commands
if [ "$1" = "ci-install" ]; then ci_install ; exit $? ; fi
if [ "$1" = "ci-bump" ]; then ci_bump ; exit $? ; fi # TODO
if [ "$1" = "ci-slack" ]; then ci_slack $2 $3 ; exit $? ; fi # TODO
if [ "$1" = "ci-build" ]; then ci_build $2 $3 ; exit $? ; fi # TODO


# Android commands
if [ "$1" = "start.a" ]; then . ./_scripts/run.and start ; exit $? ; fi
if [ "$1" = "build.a" ]; then . ./_scripts/run.and build $2 ; exit $? ; fi
if [ "$1" = "upload.a" ]; then . ./_scripts/run.and upload $2 ; exit $? ; fi # TODO

# ios commands
if [ "$1" = "start.i" ]; then . ./_scripts/run.ios start ; exit $? ; fi
if [ "$1" = "build.i" ]; then . ./_scripts/run.ios build $2 ; exit $? ; fi
if [ "$1" = "upload.i" ]; then . ./_scripts/run.ios upload $2 ; exit $? ; fi # TODO

# web commands
if [ "$1" = "start.w" ]; then . ./_scripts/run.web start ; exit $? ; fi
if [ "$1" = "build.w" ]; then . ./_scripts/run.web build $2 ; exit $? ; fi
if [ "$1" = "upload.w" ]; then . ./_scripts/run.web upload $2 ; exit $? ; fi # TODO



if [ "$1" = "doctor" ]; then ./node_modules/.bin/expo doctor ; exit $? ; fi

echo "Unknown command"
