#!/bin/sh

echo "### Checking formatting"
./run format fix
if [ $? -ne 0 ]; then exit 1; fi

echo "### Checking code errors"
./run lint
if [ $? -ne 0 ]; then exit 1; fi

echo "### Checking TypeScript types"
./run typecheck
if [ $? -ne 0 ]; then exit 1; fi

echo "Done"
