    develop:
      - step:
          name: Check code before version bump
          runs-on:
            - self.hosted
          timeout: 2m
          script:
            - *global-envs
            - *dev-envs
            # Check codebase
            - ./run ci-install
            - ./run format
            - ./run lint
            - ./run test
            # Increment version number if required when merged to dev branch
            - ./run bump
      - step:
          name: Make builds
          runs-on:
            - self.hosted
          timeout: 2m
          clone:
            depth: full
          script:
            - *global-envs
            - *dev-envs
            - ./run ci-slack "Starting dev build of $APP_NAME"
            - ./run ci-build dev
