    staging:
      - step:
          name: Make build by synch with GitHub
          timeout: 2m
          clone:
            depth: full
          script:
            - *global-envs
            - *stg-envs
            - cd $BITBUCKET_CLONE_DIR
            - git status
            - git remote add github $BUILD_REPO
            - git push --force --set-upstream github $BITBUCKET_BRANCH:$BITBUCKET_BRANCH
