    staging:
      - step:
          name: Make builds
          runs-on:
            - self.hosted
          timeout: 2m
          clone:
            depth: full
          script:
            - *global-envs
            - *stg-envs
            - ./run ci-slack "Starting staging build of $APP_NAME"
            - ./run ci-build stg
